# @package __global__

# This is the training loop solver
# for the melody MusicGen model (text+chroma to music)
# on monophonic audio sampled at 32 kHz
defaults:
  - musicgen/default
  - /model: lm/musicgen_lm
  - override /conditioner: chroma2music_custom
  - override /model/lm/model_scale: small
  - _self_

autocast: true
autocast_dtype: float16

# EnCodec large trained on mono-channel music audio sampled at 32khz
# with a total stride of 640 leading to 50 frames/s.
# rvq.n_q=4, rvq.bins=2048, no quantization dropout
# (transformer_lm card and n_q must be compatible)
compression_model_checkpoint: //pretrained/facebook/encodec_32khz

channels: 2
sample_rate: 32000

deadlock:
  use: true  # deadlock detection

dataset:
  batch_size: 64  # 32 GPUs
  segment_duration: 30
  sample_on_weight: false  # Uniform sampling all the way
  sample_on_duration: false  # Uniform sampling all the way

generate:
  every: 1000
  lm:
    use_sampling: true
    top_k: 250
    top_p: 0.0

optim:
  epochs: 400
  updates_per_epoch: 1000
  lr: 1e-4
  optimizer: adamw
  max_norm: 1.0
  eager_sync: true
  adam:
    betas: [0.9, 0.95]
    weight_decay: 0.1
    eps: 1e-8

logging:
  log_tensorboard: true

schedule:
  lr_scheduler: cosine
  cosine:
     warmup: 0
     lr_min_ratio: 0.0
     cycle_length: 1.0

#cache:
#  path: /root/cache/audiocraft_main
#  write: false
#  write_shard: 0
#  write_num_shards: 1

checkpoint:
  save_every: 250
  keep_last: 1

